---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cluster-permission
rules:
- apiGroups:
  - addon.open-cluster-management.io
  resources:
  - managedclusteraddons
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - authentication.open-cluster-management.io
  resources:
  - managedserviceaccounts
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cluster.open-cluster-management.io
  resources:
  - managedclusters
  - managedclustersets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - rbac.open-cluster-management.io
  resources:
  - clusterpermissions
  - multiclusterroleassignments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - rbac.open-cluster-management.io
  resources:
  - clusterpermissions/finalizers
  - multiclusterroleassignments/finalizers
  verbs:
  - update
- apiGroups:
  - rbac.open-cluster-management.io
  resources:
  - clusterpermissions/status
  - multiclusterroleassignments/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - work.open-cluster-management.io
  resources:
  - manifestworks
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
