apiVersion: rbac.open-cluster-management.io.open-cluster-management.io/v1alpha1
kind: MulticlusterRoleAssignment
metadata:
  labels:
    app.kubernetes.io/name: multiclusterroleassignment
    app.kubernetes.io/instance: multiclusterroleassignment-sample
    app.kubernetes.io/part-of: cluster-permission
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: cluster-permission
  name: multiclusterroleassignment-sample
spec:
  # TODO(user): Add fields here
